version: '3'

services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka_network
  akhq:
    user: root
    container_name: akhq
    image: tchiotludo/akhq
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            my-cluster:
              properties:
                bootstrap.servers: "kafka:9093"
    depends_on:
      - kafka
    volumes:
      - "./akhq-config.yml:/app/application.yml"
    networks:
      - kafka_network

#  zipkin:
#    container_name: zipkinApp
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - zipkin_network
  cartDB:
    image: postgres
    container_name: cart
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carts
    ports:
      - "5250:5432"
    volumes:
      - carts-data:/var/lib/postgresql/data

  orderDB:
    image: postgres
    container_name: order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5119:5432"
    volumes:
      - orders-data:/var/lib/postgresql/data

  userDB:
    image: postgres
    container_name: user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5200:5432"
    volumes:
      - users-data:/var/lib/postgresql/data

  productDB:
    image: postgres
    container_name: products
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    ports:
      - "5220:5432"
    volumes:
      - products-data:/var/lib/postgresql/data
networks:
#  zipkin_network:
#    driver: bridge
  kafka_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  postgres-data:
  carts-data:
  products-data:
  orders-data:
  users-data:


