eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8022
spring:
  application:
    name: emailSender

application:
  config:
    user-url: http://localhost:8100/api/v1/users

management:
  tracing:
    sampling:
      probability: 1.0


