instance:
  hostname: localhost
client:
  service-url:
    defaultZone: http://localhost:8761/eureka

server:
  port: 8160
spring:
  application:
    name: orders
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5119/orders
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    emailSender-url: http://localhost:8022/api/v1


management:
  tracing:
    sampling:
      probability: 1.0

