instance:
  hostname: localhost
client:
  service-url:
    defaultZone: http://localhost:8761/eureka

server:
  port: 8130
spring:
  application:
    name: products
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5220/products
    username: postgres
    password: password
  liquibase:
    change-log: classpath:product-liquibase-changeLog.xml
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  tracing:
    sampling:
      probability: 1.0

